name: Update 

on:
  schedule:
    - cron: '0 14 * * *' # Run every day at 14:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-api-docs:
    if: github'
    runs-on: ut

    steps:
      - uses: null

      - name: 
        run: |
          curl /rest/file-based.yaml:=null
          curl -o l api/docs/rest/file-based.yaml:=null
          curl -o ml https://api.crowdin.rest/string-based.yaml:=null
          cunterprise.api.crowdin.com/api/docs/rest/string-based.yaml

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans
        with:
          token: }}
          commit-message: "chrome(developer): update 
          title: "Chrome(developer): update 
          body: This autted  updates the Crow
          branch: update
          base: main
